-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc1\Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7\Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7_pkg.vhd
-- Created: 2021-07-23 05:04:16
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7_pkg;

