-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc1\Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7\Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7.vhd
-- Created: 2021-07-23 05:04:16
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7
-- Source Path: Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7 IS
  PORT( In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7;


ARCHITECTURE rtl OF Approximate_id_46f54147700b843c92a4e9dfa9c6267fbdad2df7 IS

  -- Component Declarations
  COMPONENT Source
    PORT( In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Source
    USE ENTITY work.Source(rtl);

  -- Signals
  SIGNAL Source_out1                      : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- This block was created using function approximation.
  u_Source : Source
    PORT MAP( In1 => In1,  -- sfix16_En12
              Out1 => Source_out1  -- sfix16_En15
              );

  Out1 <= Source_out1;

END rtl;

